Adding ruff
velis74/DynamicForms pull request #236
Opened 2023-12-11 13:24 UTC by SneakyTurtlle

2023-12-11 13:41 UTC, utement requested changes

2023-12-11 13:41 UTC, utement commented on dynamicforms_dev/management/commands/generate_fields.py
> +                    + "kwargs = {k: v for k, v in locals().items() if not k.startswith(('__', 'self', 'kw'))}",
Tega je preveč spreminjal, mislim, da bi moral ostati enak z f""

2023-12-12 11:30 UTC, velis74 approved these changes

2023-12-12 11:39 UTC, utement approved these changes

2023-12-13 07:21 UTC, utement approved these changes

2023-12-13 07:50 UTC, velis74 approved these changes

2023-12-13 07:51 UTC, merged