Edited incremental-cover-check.yml
velis74/DynamicForms pull request #237
Opened 2023-12-11 13:30 UTC by SneakyTurtlle

2023-12-11 13:58 UTC, utement requested changes

2023-12-11 13:58 UTC, utement commented on .github/workflows/incremental-cover-check.yml
V pip install dodaj še eno vrstico:
pip3 install -r requirements_test_functional.txt

tam so še dodatni dependency, da lahko izvede teste v celoti.

2023-12-12 11:31 UTC, velis74 approved these changes

2023-12-12 11:38 UTC, utement approved these changes

2023-12-12 11:39 UTC, merged