Js for simple dialog
velis74/DynamicForms pull request #49
Opened 2020-09-16 13:14 UTC by utement

2020-09-17 06:13 UTC, velis74 commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +        btn_id     = btn_id.toLowerCase();
tole je po mojem odveč?

2020-09-17 06:14 UTC, velis74 commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +  showSimpleDialog: function showSimpleDialog(title, body, buttons = []) {
modalDialog? ali kvečjemu showModalDialog? show**Simple**Dialog se mi ne zdi primeren za API...

2020-09-17 06:15 UTC, velis74 commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +    $dlg.on('show.bs.modal', function (event) {
Tole dela samo za bootstrap, za jQueryUI pa zihr ne.

2020-09-17 06:16 UTC, velis74 commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +    $dlg.on('hidden.bs.modal', function (event) {
BS, not jQuery. jQuery ima druge evente...

2020-09-17 06:17 UTC, velis74 commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +        {title: 'Cancel', callback: 'dynamicforms.simpleDlgGenericCallback'},
V kodi ne vidim te callback funkcije?

2020-09-18 10:39 UTC, utement commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +    $dlg.on('show.bs.modal', function (event) {
Za jQuery je spodaj v if-u

2020-09-21 06:18 UTC, scantron requested changes

2020-09-21 06:18 UTC, scantron commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +  showModalDialog: function showModalDialog(title, body, buttons = []) {
To ni ES5

2020-09-21 06:18 UTC, scantron commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +        $('.modal-backdrop').remove();
Tole poglej, kako bi lahko naredil z uporabo standardnih BS funkcij

2020-09-21 06:18 UTC, scantron commented on dynamicforms/static/dynamicforms/dynamicforms.js
> +        $('.modal-backdrop').remove();
https://stackoverflow.com/a/41812351/1760858

2020-09-21 08:21 UTC, merged